# -*- coding: utf-8 -*-
"""Verified prose for Chapters 5 and 6. Every numerical value is traceable to
Chapter 4 of VF_CH_1_3_4.docx. Only citations already present in the thesis
reference list are used. British spelling throughout. No markdown symbols."""

# Block kinds: "title" (bold 16pt), "h2" (bold 14pt), "h3" (bold 12pt), "body" (Normal 12pt justified)

CHAPTERS = [

# ============================ CHAPTER 5 ============================
("title", "Chapter 5 — Discussion"),

("h2", "5.1 Summary of the principal findings"),
("body", "This chapter interprets the empirical evidence reported in Chapter 4 in the light of the theoretical framework and the prior literature reviewed in Chapters 1 and 2. The general research question asked whether innovation-driven acquisitions create value for acquiring firms in the European pharmaceutical industry. The empirical design does not answer this question by contrasting acquiring with non-acquiring firms; instead, it compares two categories of completed transaction, namely innovation-driven acquisitions, in which the target contributes a material pre-completion pipeline, technology platform, or research capability, and alternative-rationale acquisitions, which are motivated primarily by scale, geographic reach, mature products, services, or organisational efficiency. Two primary outcomes were examined over the three years following completion: patent-family output, addressed by H1, and return on assets, addressed by H2. Each coefficient measures the differential post-versus-pre change associated with an innovation-driven transaction relative to an alternative-rationale transaction, and none should be read as the effect of acquiring rather than not acquiring."),
("body", "The evidence does not support H1. The analysis does not identify a statistically detectable difference in the three-year patent-family trajectories of the two acquisition categories: the estimated differential is close to zero (β = −0.46 families; wild-bootstrap p = 0.82), and this result is substantively unchanged under the inverse-hyperbolic-sine and Poisson pseudo-maximum-likelihood specifications. Because the confidence interval remains wide, at approximately [−4.52, 3.61], the finding is best characterised as an imprecise null rather than as evidence that the two categories are equivalent."),
("body", "H2 is not supported at conventional significance levels, although the baseline point estimate is directionally consistent with the predicted relationship. The estimated differential in return on assets is positive (β = +10.78 percentage points) but statistically insignificant (wild-bootstrap p = 0.40), with a wide confidence interval of approximately [−13.69, 35.24]. The influence diagnostics further show that this positive point estimate is fragile: excluding a single micro-cap acquirer reduces it to approximately +0.43 percentage points. Neither result, therefore, demonstrates equivalence between the two categories, and neither supports a strong causal conclusion. Rather than confirming a universal pattern, the findings direct attention to heterogeneity and to the conditions under which acquired innovation assets are, or are not, converted into measurable performance."),

("h2", "5.2 Interpretation of H1 — Patent-family output"),
("body", "The first hypothesis anticipated that innovation-driven acquirers would experience a relatively less favourable change in annual patent-family output than alternative-rationale acquirers in the three years following completion. The estimated differential is essentially zero and imprecisely estimated, so the anticipated negative differential is not observed. It is important to be clear about what this result does and does not say. It indicates that, on average and within this sample, the two categories of acquirer do not display measurably different three-year patent-family trajectories; it does not establish that acquisition rationale is irrelevant to innovation, nor that the two groups are equivalent."),
("body", "Several interpretations are consistent with a near-zero average differential. The first concerns the well-documented development lags of pharmaceutical research. As emphasised in the literature on innovation measurement and drug development (DiMasi et al., 2016), the interval between priority filing, clinical progression, and regulatory approval is long, and a three-year post-completion window may be too short for the innovative contribution of an acquired pipeline to register as new patent families attributable to the acquirer. A related consideration is that the assets motivating an innovation-driven transaction were frequently patented by the target before completion; their scientific value may subsequently be realised through clinical progression or regulatory approval rather than through additional filings, forms of value that a family count does not capture. This distinction between patent quantity and patent quality or value is central to the measurement literature (Valentini, 2012; Hall, Jaffe and Trajtenberg, 2001), which cautions that counts and quality-adjusted measures may diverge."),
("body", "A second interpretation concerns treatment heterogeneity. The innovation-driven group is not uniform: it combines pipeline, platform, diagnostic, gene-therapy, inhalation-technology, and specialist-technology transactions undertaken by acquirers ranging from large pharmaceutical groups to small biotechnology and specialty firms. The theoretical literature on absorptive capacity (Cohen and Levinthal, 1990) and on technological relatedness (Ahuja and Katila, 2001; Cloodt et al., 2006) suggests that the innovative consequences of an acquisition depend on the compatibility between the acquired knowledge base and the acquirer's existing competences. Where relatedness and absorptive capacity are high, integration may sustain or increase inventive output; where they are low, disruption may suppress it. Averaging across such heterogeneous transactions can produce a coefficient near zero even when transaction-level effects are substantial and offsetting."),
("body", "A third interpretation concerns classification. As documented in Chapter 4, the first-stage rationale screens were subject to bidirectional error, and although the adjudication reassigned several clear cases, residual false negatives may remain among the transactions that could not be individually examined. Because false negatives place genuine innovation-driven transactions into the comparison group, they contaminate that group and attenuate any true contrast towards zero. Low statistical power compounds this: with a small number of acquirer clusters, the estimator is unlikely to detect a moderate differential even if one exists, which is precisely why the confidence interval is wide."),
("body", "It is also worth noting what the event-study evidence adds to this reading. The joint test does not reject parallel pre-trends, which lends some credibility to the comparison, but the associated confidence intervals are wide in every relative year, so the absence of a detectable pre-trend reflects limited power as much as genuine parallelism. A near-zero differential estimated with such imprecision is therefore fragile evidence on which to build any strong claim, whether of an effect or of its absence."),
("body", "Taken together, H1 is not supported, but the appropriate conclusion is cautious. The analysis does not establish equivalence between the two acquisition categories, and a near-zero average coefficient may conceal heterogeneous, transaction-specific effects that partially offset one another. The result is therefore most accurately described as an imprecise null that is compatible with development lags, measurement limitations, and residual classification error, rather than as evidence that acquisition rationale has no bearing on innovation."),

("h2", "5.3 Interpretation of H2 — Return on assets"),
("body", "The second hypothesis anticipated a more favourable post-completion change in return on assets for innovation-driven acquirers than for alternative-rationale acquirers. The estimated differential is positive, at +10.78 percentage points, and the decomposition attributes a post-period change of +2.76 percentage points to the alternative group and +13.53 percentage points to the innovation group. The direction of this estimate is consistent with the hypothesis. Nevertheless, the estimate is not statistically distinguishable from zero, its confidence interval is very wide, and, as discussed below, it is highly sensitive to influential observations."),
("body", "A positive differential of this kind is compatible with several mechanisms, although the design cannot demonstrate that any of them operated. The financial-synergy literature indicates that cost consolidation, the removal of duplicated functions, the reallocation of resources, and the exploitation of complementary manufacturing, regulatory, and commercial capabilities may improve accounting performance within a relatively short period, even where innovation output does not increase (Teece, 1986). The commercialisation of acquired assets and post-completion restructuring may also raise measured returns. A positive point estimate is therefore theoretically plausible; but plausibility is not confirmation, and the statistical insignificance of the estimate means that these mechanisms remain conjectural in the present sample."),
("body", "An alternative and more sceptical reading is equally consistent with the evidence. The innovation-driven group enters the observation window with a lower and considerably more volatile pre-period return on assets, a feature associated with the presence of small, loss-making biotechnology acquirers. When an initially weak or volatile series is observed over a subsequent period, a portion of any apparent improvement may reflect convergence from an unusually low base, or regression towards the mean, rather than an economic consequence of the transaction. Acquisition accounting introduces a further complication: changes in the asset base, restructuring expenses, integration costs, and impairments can all move return on assets in the years immediately after completion for reasons unrelated to the underlying performance of the acquired innovation. In addition, synergies typically require time to materialise, so a three-year window may capture integration costs more fully than realised benefits."),
("body", "The influence diagnostics are decisive for the interpretation of H2. The leave-one-acquirer-out analysis shows that the positive differential is concentrated in a small number of small and volatile acquirers rather than being broadly distributed. Excluding Biodexa, a micro-cap acquirer with extreme fluctuations in return on assets, reduces the differential from +10.78 to approximately +0.43 percentage points, whereas excluding Roche raises it to +14.33. A result that moves so sharply with the removal of one firm cannot be regarded as a stable, systematic pattern. The retention of serial acquirers likewise reduces the estimate, to +6.43 percentage points, underlining its dependence on sample composition."),
("body", "The event-study evidence reinforces this cautious reading. The post-completion coefficients are positive in the first two years but diminish by the third, and the joint pre-trend test does not reject parallel pre-trends; yet the pre-period differentials are not negligible in magnitude, so the parallel-trends assumption is supported weakly rather than firmly. A differential that is positive but declining, imprecisely estimated, and concentrated in a few firms is precisely the configuration in which an apparently favourable average can coexist with the absence of any systematic economic effect."),
("body", "The appropriate conclusion is therefore measured. The positive estimate is compatible with cost consolidation, resource reallocation, complementary-asset exploitation, and the commercialisation of acquired capabilities, but the analysis cannot demonstrate that financial synergies occurred. Because the estimate appears to be driven by a small number of volatile acquirers rather than by a broad and systematic tendency, H2 should be described as directionally consistent but statistically unsupported and fragile, and it should not be characterised as confirmed."),

("h2", "5.4 Comparison with previous literature"),
("body", "The findings can be located within the existing literature by considering, in turn, the points of agreement, the points of difference, and the methodological reasons why the present results need not contradict earlier work. The intention here is not to restate the review presented in Chapters 1 and 2 but to interpret the two headline results against the studies already discussed there."),
("body", "With respect to agreement, the H1 result is broadly compatible with the strand of research that reports conditional or heterogeneous, rather than uniformly negative, innovation consequences of acquisitions. Ahuja and Katila (2001) and Cloodt et al. (2006) emphasise that post-acquisition inventive performance depends on the relatedness and absolute size of the acquired knowledge base, so that outcomes vary across transactions rather than following a single sign. Cohen and Levinthal (1990) provide the absorptive-capacity foundation for this conditionality. A near-zero average differential is consistent with a setting in which such heterogeneous, offsetting effects are aggregated, and in which a short window and a quantity-based outcome further limit what can be detected."),
("body", "With respect to difference, part of the literature reports declines in patenting following consolidation, particularly where overlapping research programmes are rationalised, as discussed by Ornaghi (2009) and in the wider evidence on how mergers affect innovation (Haucap, Rasch and Stiebale, 2019). The present study does not reproduce the negative result identified in some of this research; however, the wide confidence interval does not rule out a moderate negative differential, so the evidence is better read as insufficiently precise to adjudicate than as a contradiction. Much of the earlier work also differs from the present study in ways that bear directly on comparability. Earlier studies frequently contrast acquiring with non-acquiring firms, whereas the present design compares two types of completed acquisition; they often draw on larger samples and different national settings, whereas the present analysis is confined to a small European sample; and they sometimes employ different innovation measures, whereas this study relies on simple patent-family counts over a three-year horizon. Differences in transaction definitions, in comparison groups, in classification accuracy, and in the completeness of target-level data can each generate divergent estimates without implying that any one study is incorrect."),
("body", "The financial results invite a similarly careful comparison. The literature on outsourced research through acquisition (Higgins and Rodriguez, 2006) and on financial synergies indicates that accounting performance may improve after acquisitions for reasons distinct from innovation. The possibility that innovation and financial value diverge is central to Büssgen and Stargardt (2024), who examine the differing effects of pharmaceutical mergers on innovation and financial outcomes. The pattern observed here, of a null innovation differential alongside a positive but insignificant financial differential, is directionally compatible with such an innovation–finance divergence. It is essential, however, to avoid overstating this correspondence: the present study does not empirically establish divergence, because the financial estimate is statistically insignificant and fragile, and the innovation estimate is imprecise. The literature on killer acquisitions (Cunningham et al., 2021), in which incumbents acquire and discontinue innovative targets, offers a further interpretive lens for a null or negative innovation differential, but the data used here cannot identify project-level discontinuation and so cannot test that mechanism."),
("body", "Considered as a whole, the comparison suggests that the evidence is more consistent with a heterogeneous and conditional account of pharmaceutical-acquisition performance than with a universal positive or negative effect. The results neither confirm nor conclusively contradict the prior literature; rather, they indicate that, in a small and imperfectly measured European sample, the average differences between the two acquisition categories are too weakly estimated to distinguish among the competing accounts."),

("h2", "5.5 Theoretical implications"),
("body", "The theoretical framework developed in the review provides a coherent structure for interpreting these findings, provided that theoretical consistency is not mistaken for empirical confirmation. The resource-based and knowledge-based views (Barney, 1991; Grant, 1996) hold that access to valuable, difficult-to-imitate resources and knowledge can underpin competitive advantage. The evidence here is a useful reminder that acquiring a valuable resource is not the same as converting it into measurable post-acquisition performance. Legal ownership of a pipeline, platform, or patent portfolio does not guarantee the transfer of the tacit knowledge, organisational routines, scientific judgement, and team-specific capabilities on which the value of that resource depends (Nelson and Winter, 1982). The near-zero innovation differential is consistent with the possibility that ownership was transferred while the underlying capability was not fully absorbed, although this interpretation cannot be established directly with the available data."),
("body", "The absorptive-capacity perspective (Cohen and Levinthal, 1990) and the literature on technological relatedness (Ahuja and Katila, 2001) further suggest that average effects may conceal differences in technological compatibility between acquirer and target. Where the acquired knowledge base is closely related to the acquirer's prior competences, integration is more likely to sustain inventive output; where it is distant, the same transaction may depress it. An average differential near zero is consistent with the coexistence of both patterns within the sample, which provides a plausible interpretation of the imprecise H1 result without demonstrating the underlying mechanism."),
("body", "The theory of complementary assets (Teece, 1986) offers a bridge between the innovation and financial findings. It implies that an acquirer may generate financial value from complementary manufacturing, regulatory, and commercial capabilities even without producing additional patents, since these assets support the commercialisation of existing innovation. The pattern of a null innovation differential alongside a positive, if fragile, financial differential is consistent with such a mechanism. At the same time, agency theory (Jensen, 1986) cautions that overpayment, empire-building, and the free-cash-flow problem may erode value, while integration and disruption costs may offset potential gains, particularly in the short run. The replacement and pre-emption mechanisms discussed in the review (Arrow, 1962; Gilbert and Newbery, 1982) indicate that incumbents' incentives to develop or to shelve acquired innovation may differ from those of independent firms, which may reduce observed inventive output for strategic rather than integrative reasons."),
("body", "It follows that the two hypotheses are best understood as addressing conceptually distinct questions rather than two sides of a single effect. Whether an acquired capability raises the acquirer's inventive output and whether it improves the acquirer's accounting performance depend on different mechanisms, and a firm may achieve one without the other. This is why estimating H1 and H2 under a common classification and event-time framework is analytically valuable even when neither estimate is precise: it makes visible the possibility that the innovation and financial consequences of the same transactions diverge, which a single-outcome design would obscure."),
("body", "The broader theoretical implication is that innovation and financial value operate through different mechanisms and over different time horizons, so that they need not move together within a three-year window. This is precisely the innovation–finance divergence articulated by Büssgen and Stargardt (2024). The present evidence is consistent with such divergence and may reflect it, but, given the imprecision of both estimates, the divergence cannot be established directly with the available data. The contribution of the theory here is interpretive: it renders the observed pattern intelligible and identifies the mechanisms that richer data would be required to test, rather than confirming any single mechanism as an empirical finding."),

("h2", "5.6 Managerial implications"),
("body", "Because the empirical findings are statistically inconclusive, the managerial implications are best framed as prudent responses to uncertainty rather than as prescriptions demonstrated by the regressions. The most general implication is that the value of an innovation-driven acquisition cannot be inferred from the presence of an attractive pipeline or platform alone; it depends on whether the acquirer can absorb and develop the acquired capability. This directs attention to pre-acquisition due diligence that looks beyond the headline asset to assess technological fit, pipeline quality, the strength and breadth of the underlying patents, and the degree to which value depends on a small number of key scientists whose departure would erode it."),
("body", "The evidence on heterogeneity and on the fragility of the financial result also suggests that integration capacity deserves explicit attention. Where an acquisition adds capability that overlaps with existing programmes, managers should consider the risk of therapeutic or technological duplication and the possibility that consolidation, while improving short-run accounting measures, may reduce inventive output. Protecting scientific teams and tacit knowledge, preserving an appropriate degree of research autonomy, and maintaining continuity in critical projects are plausible means of retaining the capability for which the premium was paid, even though the present study cannot quantify their effect."),
("body", "A further implication concerns how post-completion performance is monitored. The analysis indicates that no single indicator is adequate. Managers and investors should not evaluate an innovation-driven transaction using patent counts alone, since these may lag or fail to capture value; nor using one-year profitability, which is sensitive to acquisition accounting and to influential observations; nor using announced synergies, which may not be realised. A more informative approach is multidimensional, combining, where conceptually relevant, clinical progression, pipeline milestones, project continuation, scientist retention, regulatory events, patent quality, and realised financial outcomes over a horizon long enough for integration to take effect. Framed in this way, the practical lesson is one of measured caution: innovation-driven acquisitions may be strategically valuable, but their realised value is contingent and should be assessed with a broad and patient set of indicators rather than a single short-run metric."),

("h2", "5.7 Alternative explanations"),
("body", "Before drawing conclusions, it is necessary to consider whether the empirical pattern might arise from factors other than acquisition rationale. Several such explanations can be identified, and for each it is useful to state the mechanism, the result most affected, and the likely direction of any resulting bias."),
("body", "The first is that innovation-driven acquirers are systematically smaller and more financially volatile than alternative-rationale acquirers. This composition could generate an apparent financial differential through convergence from a low base rather than through any consequence of the transaction; the mechanism operates mainly on H2, and the direction of the bias is most plausibly upward, inflating the positive estimate. Regression towards the mean works in the same direction and affects the same outcome. A related concern is that extreme biotechnology-accounting ratios, arising when returns are computed for firms with very small asset or revenue bases, may produce influential outliers; the leave-one-acquirer-out evidence indicates that this mechanism materially affects H2, again in an upward direction, since the removal of one volatile acquirer collapses the estimate."),
("body", "A second group of explanations concerns data generation. Selection in Bloomberg coverage, whereby financial data are more complete for larger or listed acquirers, and uneven Lens search scopes across companies, could shape both samples in ways unrelated to rationale; the resulting bias is of uncertain direction because it depends on which firms are over- or under-represented. Residual classification error and comparison-group contamination, discussed above, principally affect H1 and are expected to bias the differential towards zero. Acquisition timing and fiscal-year alignment, whereby the completion year combines pre- and post-transaction months, could distort the event-time mapping; the primary specification omits t0 precisely to limit this, but any residual effect is of unpredictable sign."),
("body", "A third group concerns unobserved events. The assets motivating an innovation-driven transaction were often patented before completion, so that measured post-completion filings understate the acquired contribution; this depresses the apparent innovation differential. Subsequent acquisitions or other strategic events during the window, and missing data that may not be random, could each move either outcome in a direction that cannot be signed a priori. None of these explanations can be excluded with the available data, and their coexistence reinforces the central message that the two headline estimates are too weakly identified to attribute confidently to acquisition rationale alone."),

("h2", "5.8 Limitations and future research"),
("body", "The limitations of the analysis are not merely formal; they shape what the evidence can and cannot support, and each points to a corresponding improvement in future work. The most consequential limitation is the small size of the two analytical samples and the correspondingly small number of acquirer clusters. This directly produces low statistical power and wide confidence intervals, which is why both hypotheses yield imprecise estimates and why moderate effects cannot be ruled out. The natural improvement is to assemble substantially larger samples of completed European pharmaceutical transactions, which would narrow the intervals and permit the detection of moderate differentials that the present design cannot resolve."),
("body", "A second limitation concerns coverage. Bloomberg financial data and Lens patent data are available for only a subset of eligible transactions, and this coverage is neither complete nor evenly distributed across firms, which raises the possibility of selection and limits comparability. More complete and consistently scoped data collection, including uniform subsidiary mapping so that patent portfolios are attributed consistently across acquirers, would reduce this concern. A third limitation is the short three-year observation window, which may be too brief to capture the delayed innovative and financial consequences of pharmaceutical acquisitions; extending the post-completion horizon would allow late-emerging effects to be observed."),
("body", "A fourth set of limitations concerns measurement. Patent-family counts capture innovation quantity rather than value or quality, and the study was unable to construct credible citation-based or quality-adjusted measures at these cell sizes. Future work with richer data could employ cohort-normalised citation measures and quality indicators, and could supplement patent counts with clinical milestones, project progression, regulatory approval, and evidence of project continuation or termination, thereby measuring innovation value rather than volume alone. The absence of complete target patent portfolios also prevented a credible test of technological relatedness and of relative knowledge-base size, and the absence of inventor-location histories precluded any test of cross-border innovation relocation; assembling acquirer and target portfolios and inventor-country histories would allow these theoretically important dimensions to be examined."),
("body", "A fifth set of limitations concerns identification and design. The absence of project-level pipeline data means that integration failure cannot be distinguished from deliberate project termination, so that a null or negative innovation differential cannot be attributed to a specific mechanism. Poor pre-treatment balance and thin common support constrain the credibility of the comparison and make matched or weighted specifications difficult to sustain at the present sample size; larger samples with better overlap would permit stronger matching or weighting where common support allows. Finally, the staggered timing of completions and the small size of the resulting cohort cells prevented the estimation of a stronger cohort-specific or stacked event study; with more transactions per cohort, such designs could be implemented to guard against the biases associated with two-way fixed-effects estimation under heterogeneous timing. Taken together, these limitations explain why the study yields associational rather than confirmatory evidence, and they define a coherent agenda for the research that would be required to reach firmer conclusions. These considerations lead directly to the concluding chapter, which returns to the research question and states what can, and cannot, be concluded from the evidence assembled here."),

# ============================ CHAPTER 6 ============================
("title", "Chapter 6 — Conclusion"),

("h2", "6.1 Direct answer to the research question"),
("body", "This thesis asked whether innovation-driven acquisitions create value for acquiring firms in the European pharmaceutical industry. The design answers a specific and carefully bounded version of that question. It compares innovation-driven acquisitions with alternative-rationale acquisitions, both of which are completed transactions, and it therefore estimates the differential post-completion change associated with an innovation rationale, not the effect of acquiring rather than not acquiring. Within this frame, the answer is that the available evidence is insufficient to establish that innovation-driven acquisitions create either more or less value than alternative-rationale acquisitions along the two dimensions examined."),
("body", "With respect to innovation, H1 is not supported: no statistically detectable difference in three-year patent-family output is found between the two categories, and the estimate, while close to zero, is imprecise. With respect to financial performance, H2 is not statistically supported; the differential in return on assets is directionally positive, and thus consistent with the predicted relationship, but it is imprecisely estimated and highly sensitive to a small number of influential firms, falling to approximately +0.43 percentage points when a single volatile acquirer is excluded. Neither result should be read as proof that the two categories are equivalent, since imprecise estimates and wide confidence intervals leave open the possibility of moderate differences in either direction. The most accurate answer to the research question is therefore a qualified one: innovation-driven pharmaceutical acquisitions may be strategically valuable, but the evidence assembled here is not sufficient to support a precise or causal conclusion about whether they create differential value for acquirers, and it points instead to a heterogeneous and conditional pattern."),

("h2", "6.2 Main contributions"),
("body", "The contribution of the thesis is conceptual, methodological, and empirical, and in each respect it lies in how the question is framed and examined rather than in a confirmed treatment effect. The conceptual contribution is to distinguish innovation-driven from alternative-rationale acquisitions and to treat this distinction as central rather than incidental. By declining to treat all mergers and acquisitions as strategically equivalent, and by separating innovation value from financial value, the thesis clarifies what it means to ask whether innovation-motivated transactions create value and why the two outcomes need not move together."),
("body", "The methodological contribution is an observable, transaction-level classification protocol in which first-stage rationale screens are adjudicated on pre-completion evidence, classification error is made explicit and treated as bidirectional, and the resulting groups are analysed within a common event-time framework. Outcome-specific patent and financial panels are constructed so that transactions may enter one analysis without the other, and a comparative acquisition-type difference-in-differences design is applied with clustering at the acquirer-group level and inference appropriate to small samples. This protocol offers a transparent template for comparing acquisition types rather than comparing acquirers with non-acquirers."),
("body", "The empirical contribution is to bring this design to bear on completed European pharmaceutical transactions and to examine patent-family output and return on assets separately over a common horizon. In doing so, the study documents, concretely, the limitations of an acquisition-type difference-in-differences design when data are sparse, and it illustrates a pattern that is directionally compatible with innovation–finance divergence without claiming that such divergence has been confirmed. The contribution is thus an analytical framework and a body of carefully qualified evidence, not a demonstrated positive or negative effect of innovation-driven acquisition."),

("h2", "6.3 Managerial implications"),
("body", "For managers and investors, the principal lesson is that the value of an innovation-driven acquisition is contingent rather than automatic and cannot be judged from the acquired asset alone. Due diligence should therefore assess technological fit, pipeline quality, patent strength, and dependence on key scientists, and should weigh the acquirer's capacity to integrate and develop the target's capability without dissipating it. Because no single indicator proved sufficient in this analysis, post-completion performance is better monitored through a multidimensional set of measures, combining clinical progression, pipeline milestones, project continuation, scientist retention, regulatory events, patent quality, and realised financial outcomes over a sufficiently long horizon. Given the inconclusive statistical evidence, these implications are offered as prudent guidance under uncertainty rather than as prescriptions established by the results."),

("h2", "6.4 Limitations"),
("body", "The final answer is constrained by a small number of limitations that bear most directly on what can be concluded. The analytical samples are small and the acquirer clusters few, which limits statistical power and widens the confidence intervals; common support between the two groups is thin; and Bloomberg and Lens coverage is selective and unevenly scoped. Classification, although frozen before estimation, relied on evidence embedded in the transaction data rather than on archived primary filings, so that residual misclassification cannot be excluded. The observation window is short relative to pharmaceutical development, and the primary innovation measure captures patent-family quantity rather than quality or clinical value. Finally, the H2 estimate is sensitive to individual firms. These constraints are the reason the evidence is associational rather than confirmatory, and they should be borne in mind when interpreting the conclusions."),

("h2", "6.5 Future research"),
("body", "The agenda that follows from this study can be organised around better coverage, better innovation measures, and better empirical designs. Better coverage would begin with substantially larger samples of completed European transactions and longer post-completion periods, supported by consistent subsidiary mapping and by classification anchored in archived primary sources rather than in embedded descriptions. These improvements would narrow the confidence intervals and reduce the classification uncertainty that limits the present study."),
("body", "Better innovation measures would move beyond patent-family counts to cohort-normalised citations and other indicators of patent quality, and would incorporate clinical milestones, project progression, regulatory approval, and evidence of project continuation or termination, so that innovation value, rather than volume alone, could be assessed. The assembly of acquirer and target patent portfolios, together with inventor-country histories, would additionally permit tests of technological relatedness, relative knowledge-base size, therapeutic overlap, and cross-border innovation relocation, all of which the present data could not support."),
("body", "Better empirical designs would exploit larger samples to implement cohort-specific or stacked event studies that are robust to staggered completion timing, and to apply stronger matching or weighting where common support permits. Together, these directions describe the conditions under which the questions raised here could be answered with greater precision and with a firmer basis for causal interpretation."),

("body", "In conclusion, innovation-driven pharmaceutical acquisitions cannot be described, on the basis of this evidence, as uniformly creating or destroying value. Access to pipelines, technology platforms, and specialised scientific knowledge may be strategically valuable, but whether that value is realised appears to depend on integration, technological fit, timing, and the availability of complementary assets, and innovation and financial outcomes may move differently and over different horizons. The thesis contributes less through a single definitive estimate than through its classification protocol and its joint analytical framework for comparing two types of completed acquisition, and through the disciplined, cautious interpretation of what such a design can support. Firmer conclusions about whether innovation-driven acquisitions create value for European pharmaceutical acquirers will require richer data, better measures of innovation value, and larger samples than were available here; on the present evidence, the most responsible conclusion is a carefully qualified one."),
]
