# -*- coding: utf-8 -*-
"""Revised prose for the rough passages of Chapter 3 (methodology).
Every numerical value, date, variable name, equation reference, citation, and
statistic is preserved verbatim. British spelling. Informal 'we' rendered
impersonally for consistency with the rest of the thesis. Only genuinely rough,
garbled, or error-containing paragraphs are revised; clean technical paragraphs
are left unchanged."""

REVM = {

116: "The present study adopts a quantitative, explanatory, longitudinal, and comparative panel-data research design. Its purpose is to examine how the post-acquisition change in acquirers’ innovation and financial performance differs according to the strategic content of completed acquisitions in the European pharmaceutical sector. In essence, the study asks whether innovation-driven acquisitions create value for acquirers and, more specifically, how the post-acquisition change in innovation and financial performance compares between firms that completed an “innovation-driven” acquisition and those whose acquisitions were motivated by scale, geographic expansion, diversification, customer access, mature products, or operational efficiency.",

117: "A key feature of the design concerns the distinction between the two treatment groups. Every observed firm completes an acquisition, so the comparison group cannot be treated as a control group in the sense of an undisturbed group or a counterfactual with zero acquisition. The estimand is a differential treatment effect defined by acquisition-type classification—the post-versus-pre change for innovation-driven acquisitions relative to the corresponding change for alternative-rationale acquisitions—and it should not be interpreted as the effect of acquiring rather than not acquiring.",

120: "The design is quasi-experimental and should not be read as causal on its face. Because acquisition type is self-selected, a causal interpretation is warranted only where several supporting conditions are satisfied: a credible treatment classification, sufficient common support between the groups, plausible parallel pre-treatment trends, limited influence of individual firms, an adequate number of acquirer clusters, and no overlapping treatment events within the estimation window. Where these conditions are not met, the estimates are interpreted with caution as conditional associations. It is also important to distinguish the completion of data cleaning and panel construction, which the design achieves, from the credibility of causal identification, which is assessed through the diagnostics in Sections 3.13 and 3.19 and remains constrained by the small realised samples.",

125: "Six thresholds were required for a transaction to be eligible: completion; a completion date that can be reliably determined; relevance to the European pharmaceutical or biotechnology industry; an identifiable acquirer and target; a material transfer of control; and outcome coverage adequate for the model concerned. Eligible transactions are then organised into a hierarchy of samples, so that the strength of the control-transfer requirement can itself be examined.",

135: "Because the innovation and alternative-rationale screens are non-exclusive, the same transaction may appear in both initial extracts. Every overlap was therefore collapsed into a single definitive deal record. An initial comparison of the workbooks, based on an acquirer–target–year key, identified 39 overlaps. Programmatic consolidation—using normalised acquirer and target names, exact completion dates, and enriched company mappings—resolved 42 cross-file duplicates and removed 3 within-file duplicate pairs, so that the 351 candidate rows reduced to 306 distinct economic events. The figure of 42 cross-file duplicates is used consistently in this chapter and in Chapter 4, while the preliminary count of 39 is retained only to explain the reconciliation. Final classification was determined by the available evidence rather than by the extract in which a transaction originally appeared.",

137: "Bloomberg was used to obtain annual financial information for acquiring firms that could be reliably identified in the database. Financial-data collection was availability-based: the 306 consolidated transactions form the starting universe rather than the estimation sample for H2, and only acquirers with sufficient historical Bloomberg observations could enter the financial regressions. This criterion does not invalidate Bloomberg as a source, but it limits the generalisability of the findings to acquirers followed by Bloomberg, which are likely to be larger, publicly listed, and more fully disclosed than the underlying population.",

139: "Only realised, historical financial observations were retained; any fields labelled Current, estimate, forecast, LTM, or NTM, along with all forward projections, were removed. Blank cells were treated as missing, and cells containing a dash were treated as missing until confirmed as an economic zero, so that no unknown financial observation was recorded as zero. The company identifier was determined from the contents of each Bloomberg workbook—company information, ticker, fiscal year-end, and currency—rather than from the external file name.",

143: "Overlap between searches was handled by constructing an entity dictionary that linked each company to its owners, subsidiaries, and prior legal names, as well as its previous and alternative applicant names. Potential duplicates at the patent-family level were then merged across multiple application publications, applicant countries, subsidiaries, and overlapping applications, on the basis of family membership, Lens IDs, and application numbers. A company-year was assigned a value of zero only where the relevant set of owners and applicants had been searched across the full year, the subsidiary mappings had been implemented, and no eligible families were found; in all other cases the observation was retained as missing.",

146: "Transactions were classified into the two acquisition groups primarily on the basis of the contemporaneous announcement text embedded in the GlobalData deal descriptions and the reported rationale fields. Supplementary verification through official acquisition announcements, annual reports, investor presentations, target websites, and regulatory filings was intended, but these sources were not systematically retrieved and archived for every analysed transaction at the time of estimation. The resulting classification is therefore evidence-based but subject to residual measurement error, and it should not be presented as the product of a comprehensive multi-source documentary protocol.",

147: "Given this constraint, not every classification is labelled “high confidence”. Each adjudicated transaction was placed in one of six categories: provisionally verified innovation-driven, alternative-rationale, mixed or borderline, ineligible, not substantively adjudicated, or insufficient evidence. An accompanying confidence level—strongly supported, medium, or mixed—indicates the strength of the available evidence rather than documentary completeness. Every decision is recorded in the frozen classification file, together with an evidence summary and a confidence level.",

154: "At the second stage, each transaction underwent deal-level substantive adjudication. A transaction was categorised as innovation-driven where the target held a material innovation asset before completion and access to that asset was a central observable rationale for the deal. It was categorised as alternative-rationale where an efficiency-related motive—scale, geography, customer access, mature products, production, services, or operations—was the dominant observable rationale and no pipeline, platform, patent portfolio, or R&D capability formed a central part of the transaction. Only information available before completion was used, and post-acquisition outcome trajectories were not examined during classification.",

174: "Because Bloomberg and Lens.org differ in coverage, the financial and patent samples are availability-based subsets of the transaction universe and are presented separately in the attrition tables. Only data-carrying transactions—those that yielded a financial or patent outcome capable of entering a panel—were substantively resolved; the remaining transactions are recorded as not substantively adjudicated rather than as fully classified. For this reason, no table is described as a “final classification of all 306 events”. Instead, the relevant table reports the adjudication and data-availability status of the consolidated transaction universe, thereby distinguishing substantive classification from outcome-data availability.",

176: "To resolve entities across the three data sources, a versioned entity dictionary was constructed. Each mapping links a GlobalData acquirer or target name to a company name or Bloomberg ticker, to a Lens.org applicant or owner, to a prior legal name, or to a known subsidiary or relevant acquirer group. Company names cannot serve as a single automatic merge key, because abbreviations differ, corporate restructurings occur, and parent–subsidiary structures and listings may not coincide.",

177: "Wherever an exact identifier was available, it was used. Where none existed, normalised names, transaction dates, and documented parent–subsidiary relationships were used instead, and any remaining ambiguity was resolved by manual review. Fuzzy matches were only ever proposed as candidates; they were never used to assign a company identifier automatically. A proposed identifier was accepted only when supported by an exact identifier, a matching date, or documentary evidence of a parent–subsidiary relationship.",

182: "It is essential to recognise that the firms in the Bloomberg and Lens.org samples need not coincide. The estimation samples for H1 and H2 are not assumed to overlap. The two panels share the same classification criteria, event-time framework, and comparative estimand, but they draw on analytical samples constructed independently of one another.",

221: "ROA is the principal financial outcome and is estimated in percentage points using a linear fixed-effects DiD model. The main analysis retains the untransformed ratios. As a sensitivity check, ROA is winsorised at the 1st and 99th percentiles on a pooled basis, with the thresholds fixed before the robustness estimates were examined; winsorisation is never carried out within acquisition groups separately. Operating margin is retained only as a secondary specification, because it can be mechanically extreme for firms with very low revenues, such as pre-commercial biotechnology firms or firms with very high R&D spending; where it is used, the sample is restricted to firms with revenue of at least €50 million and the measure is winsorised.",

222: "Operating income divided by average assets is reported where sufficient statement fields are available. Consistent with the full-effect interpretation of the baseline model, no post-treatment variable is included as a control for the year-on-year outcome, since doing so would absorb part of the total post-acquisition association.",

224: "Standard errors are clustered at the acquirer-group level, reflecting the concern that serial correlation and repeated events might otherwise understate sampling variability (Bertrand et al., 2004). The realised samples contain approximately twelve to thirteen acquirer clusters. Because this number is too small for exclusive reliance on asymptotic cluster-robust inference, the analysis supplements cluster-robust standard errors with a restricted wild-cluster bootstrap using Rademacher weights and 1,999 replications. Statistical interpretation therefore relies on confidence intervals, the size of the economic effect, the pre-treatment mean, and sensitivity to individual firms, rather than on p-values alone. A limitation of the estimation environment should also be noted: the intended R toolchain—fixest, fwildclusterboot, wildboottestjlr, and clubSandwich—was unavailable at the time of estimation. The point estimates and the restricted wild-cluster bootstrap were consequently produced in Python using a hand-coded routine. Results were cross-checked across the linear fixed-effects, PPML, and IHS specifications, but independent replication in R has not yet been completed. Replication using the intended packages and unit-testing of the bootstrap routine are recorded as outstanding validation steps, so the custom bootstrap should not be described as fully validated.",

231: "To maintain a stable classification, only pre-completion evidence was used, and the classification file was frozen before any post-acquisition results were examined. This procedure prevents outcome information from influencing assignment to the treatment category.",

242: "The robustness programme tests sensitivity to classification, transaction scope, event timing, comparability, and outcome construction. The principal tests are as follows:",

}
