# -*- coding: utf-8 -*-
"""Revised prose for the Introduction and literature review (paras 24-113).
Every in-text citation is preserved verbatim. British spelling. No numbers changed.
The unsupported citations in P68 (Aghion et al. 2009; Azoulay and Crémieux 2006;
Blanes-Vidal and Ciocco 2012) are retained but flagged, since they do not appear
in the reference list."""

REV = {

# ---------------- Introduction ----------------
24: "The pharmaceutical industry is among the most research-intensive sectors of the global economy. Firms operate under high research and development (R&D) costs, protracted development cycles, and considerable technological and regulatory uncertainty. As the estimated cost of bringing a new drug to market has continued to rise, the pressure to find alternative means of sustaining innovation and international competitiveness has intensified (DiMasi et al., 2016). It is against this background that mergers and acquisitions (M&A) have become a principal strategic mechanism through which firms obtain external innovation assets—R&D pipelines, technology platforms, patents, and clinical-stage products—rather than developing every capability in house.",

25: "Although the literature on M&A is extensive, earlier work concentrated largely on financial performance and market concentration. More recent studies have instead treated acquisition as a process capable of shaping innovation performance and long-term value creation, particularly in knowledge-intensive industries such as pharmaceuticals (Hitt et al., 1991; Cloodt et al., 2006). Consistent with the open-innovation paradigm, a growing body of evidence indicates that pharmaceutical firms use innovation-driven acquisitions to complement, or to substitute for, internal research by securing access to external sources of innovation (Higgins & Rodriguez, 2006).",

26: "These questions are especially pertinent to the European pharmaceutical industry. Most empirical studies have been conducted in the United States, yet the European institutional framework—its regulation, pricing, and market size—differs in ways that are likely to affect both the incentives to undertake innovation-driven transactions and the manner in which such transactions create value.",

27: "Firm-level evidence on these associations in Europe nevertheless remains comparatively scarce. A clearer understanding of how innovation-driven M&A affects acquiring firms would inform the investment decisions of equity investors, the assessment and management of transaction performance, and the concerns of policymakers about the consequences of consolidation for innovation and public welfare.",

28: "The present study departs from much of this earlier work by comparing two types of completed transaction rather than contrasting acquiring with non-acquiring firms. It asks, more specifically, whether an innovation rationale is associated with distinctive post-acquisition trajectories, and whether innovation and financial value tend to move together or to diverge.",

29: "The remainder of this review is organised as follows. Section 1 sets out the theoretical foundations and examines the competing mechanisms through which acquisitions may create or destroy value. Section 2 defines the two acquisition categories and considers classification and measurement error. Section 3 reviews post-acquisition innovation performance and develops H1, and Section 4 turns to financial performance and develops H2. Section 5 discusses the identification implications of comparing two self-selected acquisition types, and Section 6 treats the mechanisms that are not tested here as a future-research agenda. Section 7 identifies the research gap and contribution, after which the conclusion establishes the link with the methodology presented in Chapter 3.",

# ---------------- 1. Theoretical foundations ----------------
31: "The theoretical literature yields no single prediction about the consequences of acquisition. Several perspectives explain how access to external knowledge may create value; others show how that value may be dissipated. Considering these mechanisms together clarifies why innovation and financial outcomes are estimated separately in this thesis, and why the relevant comparison is between two acquisition rationales rather than between acquisition and its absence.",

33: "The resource-based view offers a useful framework for explaining why a pharmaceutical firm might acquire an innovative target rather than develop comparable assets internally. Barney (1991) argues that sustained competitive advantage derives from resources that are valuable, rare, difficult to imitate, and not readily substitutable. In the pharmaceutical setting, such resources may include patented molecules, preclinical and clinical-stage pipeline assets, proprietary research platforms, clinical data, and highly specialised scientific expertise. Part of their value lies in their legal protection and in the difficulty a competitor would face in replicating the underlying tacit knowledge. By acquiring them, a firm can combine the target’s inventive know-how with its own manufacturing, regulatory, financial, and commercial capabilities, and so realise value that the target alone might not have achieved.",

35: "The knowledge-based view builds on this perspective by treating the firm as an organisation that integrates and coordinates specialised knowledge (Grant, 1996). In pharmaceuticals, that knowledge is distributed across scientific teams, laboratories, therapeutic areas, and stages of development, so acquiring a firm that already possesses complementary knowledge may be faster and less costly than reproducing it internally. Ownership, however, does not guarantee successful transfer. Nelson and Winter’s (1982) evolutionary account holds that knowledge is embedded in the organisational routines and accumulated experience through which it developed, and such routines do not move automatically when control changes hands. Legal control of a target therefore offers no assurance that the acquirer will preserve or reproduce the processes on which the target’s innovative capability depends.",

37: "Absorptive capacity refers here to a firm’s ability to recognise, assimilate, and exploit externally acquired knowledge. Cohen and Levinthal (1990) argue that this ability rests on related prior knowledge. In the acquisition context, too little technological overlap may impede communication and weaken the acquirer’s ability to assess the target’s R&D, whereas complete overlap may leave little scope for productive recombination. The evidence on subsequent innovation is broadly consistent with this view: Ahuja and Katila (2001) find that follow-on innovation depends on the attributes of the acquired knowledge base, a result echoed, within particular technology sectors, by Cloodt et al. (2006).",

38: "This evidence implies that the effects of the acquirer’s and the target’s knowledge bases are conditional on one another. Section 6 returns to this theme as a testable extension.",

# ---------------- 1.4 Complementary assets ----------------
40: "Teece’s (1986) appropriability framework emphasises that owning a technology is rarely sufficient to profit from it. Commercialisation typically requires complementary assets—manufacturing expertise, regulatory knowledge, clinical-development capability, capital, and distribution and sales networks. A large pharmaceutical acquirer may accordingly create value by combining a target’s research with downstream capabilities the target lacks. The form of the transaction may matter as well. Drawing on the Indian pharmaceutical industry, Basant and Jaiswal (2022) find that innovation outcomes differ across mergers, share acquisitions, and asset purchases. Although their institutional setting is not European, the finding that business combinations should not be treated as equivalent lends further support to distinguishing acquisitions by their rationale.",

# ---------------- 1.5 Agency, integration, disruption ----------------
42: "These value-creating explanations must be weighed against a less favourable set of mechanisms. Agency theory holds that managers may pursue acquisitions to enlarge organisational size, visibility, or control even when the expected returns to shareholders are limited (Jensen, 1986), so that potential operating gains may be offset by overpayment, restructuring and integration costs, or managerial distraction. Integration may itself destroy value where resources are redundant, organisational routines are incompatible, or key scientific personnel depart. As the knowledge-based and evolutionary perspectives suggest, such disruption may be especially damaging when the target’s inventive capability is embedded in routines that do not survive the transfer of ownership. Whether an acquisition ultimately improves performance is therefore an empirical question, and cannot be inferred from the strategic fit asserted at announcement.",

# ---------------- 1.6 Replacement and pre-emption ----------------
44: "A further explanation for lower post-acquisition innovation is deliberate commercial choice rather than failed integration. Arrow’s (1962) replacement effect implies that an incumbent has weaker incentives than an entrant to introduce an innovation that would cannibalise the profits of existing products, and Gilbert and Newbery (1982) develop a related pre-emption argument in which the incumbent invests to protect its market position. In the pharmaceutical setting, an acquirer may value an acquired project less highly when the product it targets is closely related to one the acquirer already sells or is developing. Cunningham et al. (2021) provide project-level evidence consistent with this reasoning: an acquired drug project is more likely to be discontinued when it overlaps with the acquirer’s existing pipeline, particularly in less competitive segments or where the relevant patents have long to run before expiry. The same authors nonetheless estimate that such ‘killer’ acquisitions account for only a minority of transactions.",

45: "For the purposes of this review, two concepts that are easily conflated should be kept distinct. Therapeutic overlap denotes product-market substitution—whether an acquired project competes with therapies the acquirer already holds—and is generally expected to weaken development incentives. Technological relatedness, by contrast, concerns how effectively two knowledge bases can be combined, and may bear a non-linear, potentially beneficial, relationship to innovation. The two require different data and support different interpretations. Neither is tested as a confirmatory hypothesis here; both are examined further in Section 6.",

46: "Taken together, the perspectives reviewed above do not point to a single prediction. The resource-based view, the knowledge-based view, the absorptive-capacity perspective, and complementary-assets theory explain how access to external knowledge may create value, whereas agency costs, disruption to organisational routines, weaker competitive pressure, and replacement incentives explain how value may be lost. Because these mechanisms may operate at once and in opposite directions across innovation and financial performance, the two families of outcomes must be estimated separately before any divergence between them can be examined.",

# ---------------- 2. Defining the categories ----------------
50: "The comparative design adopted in this thesis rests on a clear and observable distinction between the two acquisition categories. This section defines each category, explains why the distinction is analytically important, and then considers the classification and measurement error inherent in any rationale-based screening procedure.",

52: "An innovation-driven acquisition is defined here as a completed transaction in which the target contributes a material and identifiable innovation asset to the combined firm, and in which access to that asset constitutes a central, observable purpose of the deal. Such assets may include proprietary molecules; pre-clinical and clinical-stage pipeline assets; patents and patent families; scientific or technological platforms; specialised R&D staff; research data; discovery or clinical-development capabilities; and diagnostic tools or other R&D-enabled technologies. Each is defined by tangible characteristics observable before completion rather than by managers’ stated intentions. A transaction is not classified as innovation-driven merely because the announcement adopts the language of innovation. In the empirical design, candidate rationales such as expand offering / add products, access to resources, and forward or backward integration qualify only where the acquired assets are of the innovative types identified above.",

53: "Two qualifications clarify the boundary of this definition. First, mature commercial products, established brands, generic products, production capacity, manufacturing plants, distribution networks, sales teams, supply chains, raw materials, and ordinary downstream commercial integration are not treated as innovation assets by default, even where the stated rationale appears innovation-oriented. Second, satisfying a single criterion is not sufficient: a transaction is classified as innovation-driven only where the target held a material innovation asset before completion and access to that asset was a central purpose of the deal.",

55: "An alternative-rationale acquisition is defined here as a completed transaction whose primary purpose is not the acquisition of innovation assets. The main candidate rationales are increase scale / business expansion, geographic expansion, business diversification, operational synergy, and access to a new customer segment. Broadly, these concern organisational scale, commercial or geographic expansion, customer access, distribution, mature product portfolios, production capacity, operating efficiency, cost consolidation, and structural or organisational integration. Crucially, firms in this comparison group also complete an acquisition or merger. They do not form an untreated, non-acquiring control group; the estimand concerns the difference between two acquisition types, not the difference between acquiring and not acquiring.",

56: "Two of these candidate rationales cannot be assigned mechanically. Business diversification may be innovation-driven when it proceeds through, say, the acquisition of a gene-therapy platform, yet alternative-rationale when it involves a mature consumer-health portfolio. Operational synergy, likewise, may be innovation-driven when it integrates R&D capability and alternative-rationale when it concerns manufacturing or distribution. Transactions are therefore classified according to the underlying assets and the available evidence, rather than the rationale label alone.",

# ---------------- 2.3 Why rationale matters ----------------
58: "A rationale-based distinction is necessary because an aggregate measure of M&A pools transactions that operate through substantially different mechanisms. Ahuja and Katila (2001) find no significant post-acquisition innovation effect for non-technological transactions, while the effects of technological acquisitions vary with relatedness and the characteristics of the acquired knowledge base; Cloodt et al. (2006) report a similarly conditional pattern across high-technology sectors. Pooling the two forms of transaction would thus average over distinct mechanisms and obscure the comparison this thesis seeks to identify. The present design therefore does not ask whether acquisition in general affects outcomes, but whether an innovation rationale is associated with a different trajectory once the fact of acquiring is held constant.",

59: "A further issue is selection into acquisition type. Bena and Li (2014) show that innovation characteristics help predict which firms become acquirers and which firms combine, with transactions occurring more often where technological portfolios are linked or complementary. Phillips and Zhdanov (2013) add that the prospect of acquisition may stimulate R&D among smaller firms, while larger firms may prefer to buy innovation rather than develop it internally. Acquisition rationale is, on this evidence, far from randomly assigned, which is why a credible comparison group and an examination of pre-acquisition trends are essential—matters taken up in Section 5.",

# ---------------- 2.4 Classification and measurement error ----------------
61: "Because true managerial motive cannot be observed directly, a classification derived from disclosed transaction information is best regarded as a systematic first-stage screen rather than a perfect measure. Such a screen admits both false positives and false negatives. A false positive arises when a transaction motivated by financial or commercial considerations is assigned an innovation rationale—for example, where a mature asset base or a manufacturing or services facility is acquired without any meaningful pre-deal innovation asset. A false negative arises when a genuine pipeline, platform, or R&D capability is recorded under a rationale of scale, diversification, integration, or a purely transactional objective. Both forms of error were material in the transaction set used in this thesis and were reassigned using evidence available before completion.",

62: "Three further complications bear on the interpretation of the classification. First, mixed-motive transactions combine material innovation and commercial objectives; rather than force these into either category, the strict comparative design labels them mixed, borderline, or insufficient evidence, and either excludes them from the main comparison or retains them for sensitivity analysis. Second, the error is unlikely to be randomly distributed, since the evidence available for classification may vary across firms and over time and may be correlated with firm characteristics. Third, the direction of any resulting bias cannot be assumed in advance: false negatives in the comparison group may pull differential estimates towards zero, while false positives may add heterogeneity to the innovation-driven group. Classification error must therefore be treated as a material feature of what the estimates can be taken to show, a point revisited in the development of H1 and in the identification discussion.",

}
