# -*- coding: utf-8 -*-
"""Revised prose for literature review paras 64-113 (Sections 3, 4, 6, 7, Conclusion).
Citations preserved verbatim; British spelling; no numeric facts changed except two
documented removals of typographical artifacts (a stray heading fragment in P84 and
an orphan footnote-marker digit '7' in P88)."""

REV2 = {

64: "This section reviews the evidence on the effect of acquisition on the innovation performance of acquiring firms. It first considers evidence of negative and conditional outcomes, then distinguishes innovation quantity from innovation quality and discusses the long development lags characteristic of pharmaceuticals, before deriving the first confirmatory hypothesis.",

66: "A growing body of evidence suggests that post-completion innovation outcomes are often less favourable than the strategic arguments advanced at announcement would imply. In a broad manufacturing sample, Hitt et al. (1991) report negative associations between acquisition activity and both R&D intensity and patent intensity. In pharmaceuticals specifically, Ornaghi (2009) finds that merged firms underperform comparable non-merging firms across several measures of R&D and innovation. Using European pharmaceutical mergers, Haucap, Rasch, and Stiebale (2019) identify substantial reductions in patenting and R&D among merged firms and, in some specifications, among their non-merging rivals; the effects are largest in research-intensive markets and where the merging firms already overlap, which suggests that both competition and the organisation of research shape the outcome. These declines have commonly been attributed to the elimination of duplicated research programmes, reduced research diversity, and the discontinuation of overlapping projects discussed in Section 1.6.",

68: "These findings should not, however, be read as evidence that every acquisition reduces innovation. The studies differ in their samples, treatment definitions, outcome measures, and identification strategies. Systematic reviews by Laermann-Nguyen and Backfisch (2021) and Suo et al. (2023) report positive, negative, and statistically insignificant effects, with outcomes depending on knowledge complementarity, absorptive capacity, technological fit, and the characteristics of the acquirer and target (e.g., Aghion et al., 2009; Azoulay and Crémieux, 2006; Blanes-Vidal and Ciocco, 2012 [SOURCE OR AUTHOR VERIFICATION REQUIRED: these three works are cited in the text but do not appear in the thesis reference list; they should be added to the reference list or removed]).",

70: "An important cross-border qualification emerges from Stiebale (2016), who estimates increases in innovative activity but finds the gains concentrated in the acquiring country while activity in the target country declines. The literature thus reaches a qualified conclusion: unambiguously positive effects are the exception rather than the rule for horizontal pharmaceutical mergers, yet acquirer and target characteristics, technological overlap, and the cross-country division of research labour can still permit them. This heterogeneity provides a strong rationale for a comparison based on acquisition rationale rather than an aggregate acquisition effect.",

72: "A central difficulty in evaluating pharmaceutical innovation is that no single indicator offers a complete measure, so the assessment of an acquisition can vary with the outcome chosen. R&D expenditure is an input measure and does not reveal what that expenditure produces; a decline may reflect either weaker research effort or greater efficiency. Patent counts capture codified output but treat inventions of very different importance alike. Forward citations can signal technological impact, but Hall, Jaffe, and Trajtenberg (2001) note that gross citation counts are affected by the age and technology field of the cited patent and are subject to truncation; they must therefore be normalised and interpreted as a quality-adjusted indicator rather than as a direct measure of commercial value. Valentini (2012) likewise highlights the potential divergence between quantity and quality: an acquisition may raise the number of patents while lowering their impact, novelty, and generality, so that a simple count could suggest greater innovation even as the underlying inventions become less inventive.",

73: "Büssgen and Stargardt (2024) examine outcomes beyond patents and find no evidence of improved innovation following mergers. For the purposes of this thesis, the annual count of unique simple patent families ordered by earliest priority date is adopted as the primary innovation outcome, since it provides a clear measure of quantity that can be obtained readily and consistently for all European acquirers. Citation-weighted output is retained only as a secondary quality measure, and only where cohort normalisation and adjustment for truncation can be implemented credibly. Pipeline-stage indicators, although conceptually attractive, cannot be assembled consistently across the sample and are therefore reserved for future research.",

75: "A further consideration is the unusually long development cycle of pharmaceutical innovation. A three-year post-acquisition window may fail to capture value embodied in late-stage pipeline products that remain in clinical development or await regulatory approval beyond that horizon. Moreover, patent-family counts dated by earliest priority year reflect the timing of invention and are not a direct indication of the commercial or clinical value later realised from an acquired programme. A zero or negative difference in patent volume within the first three years could therefore coexist with substantial acquired value that has yet to register in the chosen metric—a limitation that should be borne in mind when interpreting H1.",

77: "The development of H1 draws on three strands of the literature. First, the average-effect evidence indicates frequent declines in post-acquisition patenting, particularly where overlapping research programmes are consolidated. Second, the measurement literature supports patent-family quantity as the primary tractable outcome while cautioning that quantity and quality may diverge. Third, the development-lag argument implies that a short window is likely to understate the value of acquired assets. Taken together, and framed as a comparison against alternative-rationale acquisitions rather than against non-acquiring firms, these strands suggest that innovation-driven acquirers will experience a less favourable near-term change in patent-family output: such transactions are more likely to involve the consolidation of overlapping research, whereas alternative-rationale acquisitions are more often driven by scale, geography, or efficiency.",

80: "The phrase “less favourable” is intended to encompass a range of patterns: a sharper decline, a slower rise, or a flat trajectory for the innovation-driven group while the alternative-rationale group holds steady or improves. The hypothesis is comparative and associational; it does not estimate the effect of acquisition relative to non-acquisition. Given the possibility of development lags and residual classification error, the expected relationship should be read as an average tendency rather than as a pattern that must hold for every transaction.",

# ---------------- 4. Financial performance ----------------
82: "This section turns to the financial dimension of value creation. It reviews the synergies and risks associated with pharmaceutical acquisitions, considers the implications of alternative financial measures, and examines the possibility that financial and innovation outcomes may diverge, before developing the second confirmatory hypothesis.",

84: "An acquisition may yield economic benefits even where innovation is unchanged or lower under the acquirer’s management. Such benefits include spreading fixed operating, marketing, and R&D costs over a larger base, eliminating duplication, using resources more efficiently, and commercialising existing assets across a wider market; financing and tax savings may also arise, and the acquirer may secure control of a research option rather than having to reproduce a costly capability from scratch. These arguments are consistent with the external-R&D interpretation advanced by Higgins and Rodriguez (2006) and with the transaction evidence of Danzon et al. (2007), who show that outcomes depend on firm characteristics and industry conditions. One implication is that cost and scale benefits may raise profitability without generating additional innovation, opening the possibility of the divergence discussed below.",

86: "Several countervailing factors may nonetheless suppress or postpone financial gains. Overpayment transfers value to target shareholders; restructuring and integration costs reduce near-term earnings; and the expansion of the asset base, together with acquisition accounting, may depress return-based measures even where underlying operations remain sound. Agency-driven empire-building (Jensen, 1986) may amplify these effects when transactions are undertaken for organisational size rather than expected return. Short-run profitability may consequently become volatile after completion. The sign of the financial effect is thus an empirical question and cannot be inferred from the strategic fit asserted by management.",

88: "The choice of metric and horizon shapes any conclusion about financial performance. Announcement returns capture the market’s current estimate of short-run outcomes, whereas accounting measures reflect longer-run operational performance, though the latter may be distorted by purchase-price accounting, restructuring costs, or changes in the asset base. Revenue may rise simply because the combined firm is larger, and return on assets may fall immediately as goodwill inflates total assets. The primary measure of financial performance in this thesis is Bloomberg’s standardised return on assets (ROA), a realised accounting measure of operating profit relative to the firm’s assets that can be used directly within a firm-year, event-time framework. Operating margin serves as a secondary measure, since it can become severely negative for biotechnology firms with little revenue. Long-horizon market returns are not used, as they are more difficult to align with the firm-year difference-in-differences framework.",

90: "Financial and innovation outcomes may move in opposite directions without any theoretical inconsistency. A merged firm may, for instance, close laboratories, cut duplicate projects, and reduce staffing—improving margins while narrowing the scope of research undertaken. Conversely, sustained investment in a broad pipeline may lower profitability in the short run while generating future options. Büssgen and Stargardt (2024) report that several financial measures improve after mergers, but not uniformly and not in step with innovation performance. Both lines of argument imply that the two sets of outcomes are governed by different processes and time horizons. An improvement in accounting performance is therefore no proof that the innovation rationale succeeded, just as a reduction in patenting is no proof that value has been lost. The two dimensions must be estimated independently before their direction and timing are compared.",

92: "The development of H2 rests on the evidence concerning synergies and the possibility of innovation–finance divergence. Scale economies, cost consolidation, and complementary assets may improve accounting performance within a relatively short period, even where innovation does not increase. The relevant comparative question is whether an innovation rationale is associated with a distinctive financial trajectory relative to alternative-rationale acquisitions. Two considerations suggest a more favourable change in ROA for innovation-driven acquirers. First, such deals tend to deliver complementary assets and option value that acquirers are well placed to commercialise, given the downstream competencies they already possess. Second, alternative-rationale acquisitions are more often scale-increasing, and so may impose greater integration and asset-base strain on returns in the near term. This expected difference, however, remains a conjecture to be tested rather than a settled conclusion.",

94: "The phrase “more favourable” encompasses a larger improvement, a smaller decline, or stability in the innovation-driven group while the comparison group deteriorates. As with H1, the hypothesis is comparative and associational rather than an estimate of acquisition relative to non-acquisition, and its interpretation depends on the measure and horizon chosen. Estimating H1 and H2 under a common classification and event-time framework offers a direct means of examining whether financial and innovation value move together or become decoupled across the two acquisition types.",

# ---------------- 6. Theoretical extensions ----------------
96: "Several mechanisms once formulated as confirmatory hypotheses remain theoretically important but cannot be tested credibly with the data available for this thesis. They are therefore retained as theoretical extensions, and for each the additional data required for credible testing are specified. This approach preserves their contribution to the conceptual argument while confining the confirmatory empirical design to H1 and H2.",

98: "The literature suggests that the relationship between technological relatedness and post-acquisition innovation may follow an inverted-U pattern: low relatedness may impede communication and assimilation, high relatedness may render the two knowledge bases redundant, and a moderate degree may afford the greatest scope for recombination (Ahuja & Katila, 2001; Cloodt et al., 2006; Valentini, 2012). A valid test would require the pre-announcement patent portfolios of both firms, classified by IPC or CPC patent-family categories, from which an overlap or cosine-similarity score and its square could be constructed. Given the incompleteness of target-level data, relatedness is retained as a possible explanation—entered, where feasible, as an additional regression term—rather than as a further hypothesis for confirmatory testing.",

100: "A related proposition is that a target knowledge base that is large relative to the acquirer’s may impose an integration burden and reduce subsequent innovation (Ahuja & Katila, 2001; Cloodt et al., 2006; Valentini, 2012). Testing it would require comparable pre-acquisition patent stocks for both firms, so that the ratio of target to acquirer patent stock could be interacted with the post-acquisition term. Because target-level patent coverage is incomplete, the mechanism is treated as an exploratory, future-research proposition rather than a tested hypothesis.",

102: "There is evidence that cross-border acquisitions may shift the geographical location of innovative activity. Stiebale (2016) finds that innovation may rise in the combined entity even as it falls in the target’s home country. A credible test would require inventor-country histories, which indicate where inventive activity actually takes place, rather than owner country or patent jurisdiction, which mainly reflect legal ownership. Since the available patent records do not provide consistent inventor-location histories that can be traced before and after completion, this proposition is not tested here.",

104: "Therapeutic overlap refers here to product-market substitution between an acquired project and the acquirer’s existing portfolio. It may help to distinguish unsuccessful integration from a deliberate decision to discontinue a competing project, consistent with the replacement and pre-emption incentives discussed in Section 1.6 and with the project-level evidence of Cunningham et al. (2021). A formal test would require consistent project-level information on therapeutic areas, mechanisms of action, clinical stages, project continuation or termination, and product-market overlap. As these data cannot be assembled consistently across the sample, therapeutic overlap and pipeline continuation are retained as theoretical mechanisms and directions for future research rather than confirmatory hypotheses. Therapeutic overlap should be kept distinct from the technological relatedness of Section 6.1: the former concerns product-market competition, the latter the compatibility of knowledge bases.",

# ---------------- 7. Research gap ----------------
106: "Although the literature on pharmaceutical acquisitions is substantial, important gaps remain. First, the project-level evidence on therapeutic overlap has relied predominantly on US data, whereas European firm-level work has concentrated on patents and R&D. Second, studies of innovation and of financial returns are often separated by differences in samples and research designs. Third, the pronounced heterogeneity reported across studies suggests that aggregating all acquisitions may conceal effects that depend on the underlying transaction mechanism.",

107: "Against this background, the thesis makes several contributions. The first is to distinguish innovation-driven from alternative-rationale acquisitions using observable pre-completion assets and evidence. The second is to compare two categories of completed acquisition rather than aggregating all transactions or contrasting acquirers with non-acquirers. The third is to examine financial and innovation outcomes separately within a single taxonomy and event-time framework. The study also focuses on European pharmaceutical transactions, which, to the author’s knowledge, have not previously been examined in this way, and it treats classification error and the presence of completed acquisitions in the comparison group as material features of the design, testing whether financial and innovation outcomes depend on the type of deal.",

108: "The limits of this contribution should be stated plainly. The thesis does not estimate the effect of M&A relative to non-acquisition; it does not test technological relatedness, relative knowledge-base size, cross-border innovation relocation, or therapeutic overlap as confirmatory hypotheses; and it does not claim causal identification beyond that supported by the comparative difference-in-differences design and its stated assumptions. The design cannot remove every potential source of endogeneity. Its assumptions are, however, made explicit, the comparison group is defined appropriately, and the two dimensions of value creation are examined within a coherent empirical framework.",

# ---------------- Conclusion of the review ----------------
110: "Taken together, the literature does not support the general claim that innovation-driven acquisitions invariably create or destroy value. On the one hand, such transactions may give pharmaceutical firms access to scarce technologies and to the complementary capabilities required for commercialisation. On the other, they may disrupt existing routines, narrow the scope for independent research, and weaken incentives to develop projects that compete with the acquirer’s portfolio. European evidence on horizontal mergers typically reports a decline in patenting and R&D, while cross-border evidence shows that an overall increase in activity may mask a decline in the target’s home country. The combined evidence thus points to offsetting mechanisms—resource and knowledge complementarities and absorptive capacity on one side, and agency costs, integration disruption, and replacement incentives on the other—that may act simultaneously and in opposite directions on both innovation and financial performance.",

111: "One consequence of these offsetting mechanisms is a potential divergence between financial and innovation value. Cost savings from scale economies, consolidation, and shared assets may raise book profits even where innovation does not grow, and the reverse may hold over longer horizons. This anticipated divergence forms part of the motivation for the thesis and the reason for analysing the two dimensions within a single framework.",

112: "On the basis of this review, the thesis carries forward two confirmatory hypotheses: relative to alternative-rationale acquirers, innovation-driven acquirers are expected to experience a less favourable near-term change in patent-family output (H1) and a more favourable near-term change in return on assets (H2). Technological relatedness, relative knowledge-base size, cross-border innovation relocation, therapeutic overlap, and pipeline continuation are identified as propositions for future research rather than tested hypotheses, since the data required for credible testing are not available.",

113: "The empirical strategy applies a difference-in-differences and event-study framework to compare the post-completion performance of two types of completed European pharmaceutical acquisition, alternative-rationale and innovation-driven. The outcomes examined are the stock of patent families and return on assets, organised under a common classification and event window. The aim is neither to assume that all mergers have identical effects nor to test mergers against non-mergers; it is to estimate the differential relationship associated with an innovation rationale and to assess when the two outcomes diverge or move together. The next chapter sets out the methodology through which this comparative design is implemented.",

}
